<?php

/**
 * @file
 * Contains dd_organization.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dd_organization_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dd_organization module.
    case 'help.page.dd_organization':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DD Organization') . '</p>';
      return $output;

    default:
  }
}
