<?php

/**
 * Implements hook_field_widget_info_alter().
 *
 * Allows stripe_checkout widget to be applied to number fields.
 */
function stripe_checkout_field_widget_info_alter(array &$info) {
  $info['number']['field_types'][] = 'stripe_checkout';
}

/**
 * Implements hook_theme().
 */
function stripe_checkout_theme($existing, $type, $theme, $path) {
  return array(
    'stripe_checkout' => array(
      'variables' => array(
        'action'=> NULL,
        'anon_url' => NULL,
        'price' => NULL,
        'data' => NULL,
        'logged_in' => NULL,
        'entity_id' => NULL,
        'field_name' => NULL,
      ),
    ),
  );
}
