<?php

/**
 * @file
 * Contains dd_video.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dd_video_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dd_video module.
    case 'help.page.dd_video':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DD Video') . '</p>';
      return $output;

    default:
  }
}
