module:
  address: 0
  admin_toolbar: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  captcha: 0
  chosen: 0
  chosen_lib: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  config: 0
  config_ignore: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dd_account_dashboard: 0
  dd_action_center: 0
  dd_admin: 0
  dd_alerts: 0
  dd_base: 0
  dd_bill: 0
  dd_bill_alerts: 0
  dd_blog: 0
  dd_clip: 0
  dd_committee: 0
  dd_commentary_alert: 0
  dd_email_ca_legislator: 0
  dd_email_editor: 0
  dd_email_legislator: 0
  dd_email_ny_legislator: 0
  dd_fax_service: 0
  dd_fax_service_payment: 0
  dd_find_legislators: 0
  dd_gift_contribution: 0
  dd_hearing: 0
  dd_legislator: 0
  dd_lobbyist: 0
  dd_metrics: 0
  dd_organization: 0
  dd_payment_system: 0
  dd_person: 0
  dd_search: 0
  dd_utterance: 0
  dd_video: 0
  dd_video_alert: 0
  dd_video_editor: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  facets: 0
  field: 0
  field_collection: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  filter_perms: 0
  google_analytics: 0
  help: 0
  history: 0
  html_field_formatter: 0
  image: 0
  jquery_colorpicker: 0  
  key: 0
  link: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  migrate_upgrade: 0
  multiselect: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  pathauto: 1
  quickedit: 0
  r4032login: 0
  rdf: 0
  recaptcha: 0
  redirect: 0
  request_parameter_condition: 0
  rest: 0
  s3fs: 0
  search_api: 0
  search_api_solr: 0
  serialization: 0
  shortcut: 0
  stage_file_proxy: 0
  stripe_api: 0
  stripe_checkout: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_autocomplete_filters: 0
  views_data_export: 0
  views_field_view: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_summary_rows: 0
  views_ui: 0
  menu_link_content: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  zen: 0
  dd: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
