<?php

/**
 * @file
 * Contains dd_metrics.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function dd_metrics_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the dd_metrics module.
    case 'help.page.dd_metrics':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('DigitalDemocracy Metrics / Stats') . '</p>';
      return $output;

    default:
  }
}
